FROM python:3.12-slim AS runtime

COPY requirements.txt .
RUN pip install --no-cache-dir --require-hashes -r requirements.txt

RUN adduser --disabled-password --gecos '' appuser \
 && chown -R appuser /app
USER appuser