name: Check License
permissions:
  contents: read

on:
  pull_request:
    branches: [ main, dev, testing ]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run license check
        run: python .github/scripts/check-license.py